### PR TITLE
🐛 fix explorer and r&w algolia hit clicks not being tracked correctly

### LINKED ISSUE #2932: Search clicks for charts and explorers aren't being tracked properly
Este noted that our Algolia analytics are showing implausibly low clickthrough rates - 0% almost everywhere. Presumably this is because clicks aren't being tracked and not that people aren't clicking things. We need to verify this data is being tracked properly for Charts and Explorers.

### PR DESCRIPTION
**Pull request by ikesau**
Resolves #2932

It was a simple hardcoded value that was causing the hit clicks not to be tracked.

Before, all events were being sent as:

```json
{
    "events": [
        {
            "eventType": "click",
            "index": "charts",
            "queryID": "blah",
            "objectIDs": ["global-food-2"],
            "positions": [1],
            "eventName": "click",
            "userToken": "blah",
        },
    ],
}
```

which meant Algolia wasn't able to resolve them to any actual results in the index.

I'm waiting for the analytics data to update in our owid-staging application to confirm this has fixed it and then we should be good to go.

### CODE REVIEW

File: site/search/SearchPanel.tsx [hunk 1]
```diff
@@ -429,11 +430,7 @@ export class InstantSearchContainer extends React.Component {
 
     constructor(props: Record<string, never>) {
         super(props)
-        this.searchClient = algoliasearch(ALGOLIA_ID, ALGOLIA_SEARCH_KEY, {
-            queryParameters: {
-                clickAnalytics: "true",
-            },
-        })
```
Comment (ikesau) [inline site/search/SearchPanel.tsx:436]: This wasn't doing anything, as event tracking is determined by `hasClickAnalyticsConsent` referenced elsewhere in this file.

Comment (marcelgerber) [reply site/search/SearchPanel.tsx:436]: You're right; I checked this and indeed, a `queryID` is returned by Algolia as expected.

**Review by marcelgerber — APPROVED** [review]
It can be so easy, thank you!
Tested this in DevTools on the staging site; and it is now definitely sending the correct index name, and the `queryID` also works fine.
