### PR TITLE
fix(grapher): don't offer non-plottable entities for selection

### LINKED ISSUE #1341: StackedArea allows selecting entities for which there is no data
## Description

Some StackedArea charts show entities in select dialog that we seem to have no data for:

- Seems like only regions and the World have data, but many countries are listed: https://ourworldindata.org/grapher/vegetable-oil-production?country=~IDN
- https://ourworldindata.org/grapher/per-capita-consumption-of-cereals-by-commodity-type-daily-kilocalories?country=~AGO

## Expected behaviour

Entities without (plottable) data should not be listed in select dialog for StackedArea.

### PR DESCRIPTION
**Pull request by sophiamersmann**
- fixes #1341

### Problem

- Fixes a bug where entities were offered for selection that couldn't be plotted
- This happened for:
    - StackedArea and StackedBar charts (default settings)
    - LineCharts if the config's `missingDataStrategy` was set to `hide`

### Technical details

-  The chart interface is extended by an additional (but optional) chart table transform, `transformTableForSelection`
    - If given, `transformTableForSelection` is responsible to exclude all entities that are not plottable
- `grapher.tableForSelection`calls `transformTableForSelection` of the current chart instance (if defined)
- `transformTableForSelection` has been implemented for a subset of chart types whose entity selector was sometimes buggy (see above)
    - it runs basic clean up transforms, interpolation, and the filter transforms that implement the specified missing data strategy (only if necessary)

### CODE REVIEW

File: packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx [hunk 1]
```diff
@@ -300,6 +300,26 @@ export class LineChart
...
+            table = table.replaceNonNumericCellsWithErrorValues(
+                this.yColumnSlugs
+            )
+
+            const groupedByEntity = table.groupBy("entityName").map((t) => {
+                if (t.hasAnyColumnNoValidValue(this.yColumnSlugs)) {
+                    t = t.dropAllRows()
+                }
+                return t
+            })
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx:316]:
```suggestion
            const groupedByEntity = table.groupBy("entityName").filter((t) => 
                !t.hasAnyColumnNoValidValue(this.yColumnSlugs)
            )
```

File: packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx [hunk 2]
```diff
@@ -300,6 +300,26 @@ export class LineChart
...
+            table = groupedByEntity[0].concat(groupedByEntity.slice(1))
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx:317]: This expects `groupedByEntity.length > 0`, which I'm not sure is always the case.

**Review by marcelgerber — CHANGES_REQUESTED** [review]
Nice work, overall I think this makes sense.

However, I'm thinking that the whole `tableForSelection` concept is hindering us a bit, and it would be a bit more straightforward to just make `availableEntities` an (optional) chart instance getter.

That way, any charts could run some code to tell grapher which entities they have available (potentially by running table transforms), and otherwise, they just default to `this.inputTable.availableEntities`.
Overall, just getting rid of the `tableForSelection` indirection in between. An OwidTable is not the best format to communicate available entities, I think...

File: packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx (hunk 2 above)
Comment (sophiamersmann) [reply packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx:317]: I think it's very likely since all entities being removed would be an extreme edge case, but I can guard against it in any case...

**Comment by sophiamersmann** [comment]
mhh.. I mean for now we're only grabbing the available entities, but I imagine that Christian builds the new entity selector on top of a table – so we might be a little more flexible in the future if chart instances were allowed to customise that table (cc @samizdatco)

File: packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx [hunk 3]
```diff
@@ -84,6 +84,31 @@ export class AbstractStackedChart
...
+                    table = table.interpolateColumnLinearly(slug)
+                })
+            }
+
+            const groupedByEntity = table
+                .groupBy("entityName")
+                .map((t: OwidTable) =>
+                    t.dropRowsWithErrorValuesForAnyColumn(this.yColumnSlugs)
+                )
+            table = groupedByEntity[0].concat(groupedByEntity.slice(1))
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx:106]: I think we should also have the guard against `groupedByEntity.length === 0` here.

Comment (sophiamersmann) [reply packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx:106]: lol yes, sorry for making you spell this out twice 🤪

**Review by marcelgerber — APPROVED** [review]

**Comment by samizdatco** [comment]
> mhh.. I mean for now we're only grabbing the available entities, but I imagine that Christian builds the new entity selector on top of a table – so we might be a little more flexible in the future if chart instances were allowed to customise that table (cc @samizdatco)

I didn't change much in terms of how the entity-selector populates its list of items: they're still coming from the grapher object's `selection` attribute (and in particular that `SelectionArray`'s `availableEntities` list): https://github.com/owid/owid-grapher/blob/dbe6f217514d6e18326c9a92667ed4b590b871d4/packages/%40ourworldindata/grapher/src/modal/EntitySelectorModal.tsx#L111-L118
