### PR TITLE
fix(StackedArea): render the bottom series only within the domain of data availability

### LINKED ISSUE #2133: Faceting: Stacked area chart shows incline where there's missing data
## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/electricity-prod-source-stacked?stackMode=relative&facet=entity&country=OWID_WRL~Africa~AFG
2. Notice that Afghanistan shows data from 1985, but actual data points only start beginning 2000
3. Instead, unselect the other two countries and only look at Afghanistan
4. Now the x axis is restricted to 2000+.

## Screenshots

With faceting:
image

Only looking at Afghanistan:
image

## Additional context

The issue is happening for both Relative and absolute mode, but only for the dimension at the bottom of the chart.

For Stacked area charts, we "connect the dots" between a set of dots that we compute. Here, probably, we have a dot for `(1985, 0)` and one for `(2000, xyz)`, with nothing in between.

Not sure why it's only happening for the bottom dimension.

The fix is probably to start with the first dot in the first year with data - i.e. 2000 in this case.

### PR DESCRIPTION
**Pull request by marcelgerber**
Fixes #2133.

In working on this I noticed a bunch more issues in this, so this ended up as a bit of a refactor.
It also got quite a bit more complex sadly, so if you see any way to simplify any of this (or add helpful comments at the very least) then please do let me know!

Before/afters (left/right):
image
⬆️ Here, the red incline on the left/right is misleading.

image
⬆️ Here, there's no data for Afghanistan for years <2000, but we're displaying it as if there was data.

The SVG tester comes back with many errors sadly, but these are only rounding errors as far as I can see.

### CODE REVIEW

File: packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx [hunk 1]
```diff
@@ -49,35 +56,92 @@ class Areas extends React.Component<AreasProps> {
...
+            if (index > 0) {
+                prevPoints = placedSeriesArr[index - 1].placedPoints
+            } else {
+                prevPoints = prevPoints = [
+                    [placedPoints[0][0], verticalAxis.range[0]],
+                    [
+                        lastOfNonEmptyArray(placedPoints)[0],
+                        verticalAxis.range[0],
+                    ],
+                ]
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx:142]: This is what fixes #2133 already: roughly, going from
```ts
prevPoints = [bottomLeftOfAxis, bottomRightOfAxis]
```
to
```ts
prevPoints = [bottomLeftOfPlacedPoints, bottomRightOfPlacedPoints] // where these are at y=0
```

**Comment by sophiamersmann** [comment]
Makes sense to me and I think your refactor makes the code much more readable 👏🏻 

I can't make out why these rounding issues would happen that make most stacked area charts fail. Do you know?

**Comment by marcelgerber** [comment]
> I can't make out why these rounding issues would happen that make most stacked area charts fail. Do you know?

Yes, I know.

Before, we had
```ts
const xBottomLeft = [horizontalAxis.range[0], verticalAxis.range[0]]
const xBottomRight = [horizontalAxis.range[1], verticalAxis.range[0]]
```
as the "bottom" points (the bottom points of the bottom series).
Here, `horizontalAxis.range[0]` has up to three decimal places it seems.
We are now _basically_ using `horizontalAxis.place(series.points[0].position)` instead, which [is rounded to a single digit](https://github.com/owid/owid-grapher/blob/378b440e460ae3c8b0efaa4bb7dc4cf15693d6d2/packages/%40ourworldindata/grapher/src/axis/Axis.ts#L374) instead.

Maybe it makes sense to push a small commit to master that applies this rounding on master already, just so we can get a cleaner diff.

**Comment by marcelgerber** [comment]
I now managed to produce a clean diff: https://github.com/owid/owid-grapher-svgs/compare/temp-stacked-area-rounding..stacked-area-bottom-series-faceting

There's only one change, and that one is positive.

**Comment by sophiamersmann** [comment]
Nice! Feels really good to ship so many fixes for faceted stacked area charts 🎉

**Review by sophiamersmann — APPROVED** [review]
