### PR TITLE
Adjust facet control design to accommodate entity types of arbitrary length

### LINKED ISSUE #2159: Custom "country/region" entity type shortened to "item" in "Split by ...." dropdown
## Description

Entity is sometimes described as "country/region", sometimes described as "item"

## Expected behaviour

Not sure what a good solution would be.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/cropland-use-over-the-long-term
2. Notice that the entity selection says "Add country/region"
3. Click on facet control and notice that the label says "Split by item"

## Screenshots

Screenshot 2023-04-27 at 12 02 59

## Additional context

Usually, "item" is a sensible default to use should the given entity type be too long to show in the dropdown. But in this particular case, when the entity type is changed to "country/region", saying "country/region" in one place and "item" in another is a bit confusing. I'm bringing this up as an issue because I think we have quite a lot of charts that have countries as well as regions in them, so this is a common problem.

## Design

As suggested by Matt on [Slack](https://owid.slack.com/archives/C5BDCB2R3/p1682701879020779), we could put the labels on the bottom, then expand the height of the tooltip as needed:

Screen Shot 2023-04-28 at 10 41 39 AM

Alternatively, as suggested by Marcel, the items could also be arranged vertically with text on the right.

### LINKED ISSUE #2173: Various inconsistent labels added for country and region entities
## Background

- Grapher is a system for charting variables
- Each variable contains values for different entities over time
  - The entities can be standard things like countries or other things like crop types, fish species, or anything we like
- In the UI, whenever we talk about entities ("Select [entity]", "Split by [entity]"), we use a field `entityType`
  - By default it is "country", but it can be overridden by the author

## Problem

The majority of our charts report values over both countries and regions, but we do not appear to have a stable editorial standard for how we label those entities.

For example, we use:

- "Country" (the default)
- "Region" (in both region-only and country/region mixed cases)
- "Country & region"
- "Country/region"
- "World Region"
- "Region/Country"
- "Region/Group"
- ...and others

https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select%0D%0A++entityType%2C%0D%0A++count%28*%29+freq%0D%0Afrom%0D%0A++%28%0D%0A++++select%0D%0A++++++id%2C%0D%0A++++++config+-%3E%3E+%22entityType%22+as+entityType%0D%0A++++from%0D%0A++++++charts%0D%0A++++where%0D%0A++++++entityType+is+not+null%0D%0A++%29%0D%0Agroup+by%0D%0A++entityType%0D%0Aorder+by%0D%0A++freq+desc

## Proposal

Since this is our most common case, we should not overriding the entity name for it. If we believe the default name "country" is not good enough, we should consider replacing it with a better default.

Options could include:

- "Region" (to mean country or country-aggregate)
- "Area"
- "Location"
- "Country or region"

### PR DESCRIPTION
**Pull request by sophiamersmann**
fixes #2159 | fixes #2173 | [Slack discussion](https://owid.slack.com/archives/C5BDCB2R3/p1682701879020779)

This PR solves two problems:
- Overwriting the default entity type "country" can lead to a confusing UI
- "Country" is a poor default since most of our charts contain countries and regions

### Problem 1: Overwriting the default entity type "country" can lead to a confusing UI

See #2159 for a description of the problem

This PR implements the following design that was suggested by Matt:

Screenshot 2023-05-02 at 12 56 41

#### Technical details

- The height of the tooltip expands as necessary to make "Split by [...]" fit (used to be fixed height)
- The width of the dropdown control expands as necessary to make "Split by [...]" fit (used to be fixed width)
- Length constraint on `entityType` is dropped (I checked the [longest entity types currently in use](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select%0D%0A++entityType,%0D%0A++LENGTH(entityType)+char_count%0D%0Afrom%0D%0A++(%0D%0A++++select%0D%0A++++++id,%0D%0A++++++config+-%3E%3E+%22entityType%22+as+entityType%0D%0A++++from%0D%0A++++++charts%0D%0A++++where%0D%0A++++++entityType+is+not+null%0D%0A++)%0D%0Agroup+by%0D%0A++entityType%0D%0Aorder+by%0D%0A++char_count+desc) to make sure this look ok)

#### Screenshots

New design on desktop:

Screenshot 2023-05-02 at 14 35 21

New design on mobile (iPhone SE, 375x667)

Screenshot 2023-05-24 at 13 46 17

Not optimal that the facet control is hidden on smaller screens in the default case.

---

### Problem 2: "Country" is a poor default since most of our charts contain countries and regions

See #2173 for a description of the problem

A better default is "country or region", as suggested by Ed on [Slack](https://owid.slack.com/archives/C5BDCB2R3/p1682701879020779)

#### Changes

- Default entity type is changed from "country" to "country or region"
- Default entity type (plural) is changed from "countries" to "countries or regions"

Note that `entityTypePlural` is only used in scatter plots at the moment:

Screenshot 2023-05-02 at 12 40 32

I'm happy to clean up entity types of existing charts once this is merged.

### CODE REVIEW

**Comment by sophiamersmann** [comment]
Nice! Thanks for the review!

**Comment by sophiamersmann** [comment]
Currently deployed to my staging server: https://kelley-owid.netlify.app/

File: packages/@ourworldindata/grapher/src/controls/Controls.tsx [hunk 1]
```diff
@@ -171,19 +172,20 @@ export interface FacetStrategyDropdownManager {
 export class FacetStrategyDropdown extends React.Component<{
     manager: FacetStrategyDropdownManager
 }> {
+    static contextType = MoreButtonContext
+
     render(): JSX.Element {
-        return (
+        return this.context.isWithinMoreMenu ? (
+            <div style={{ whiteSpace: "normal" }}>{this.content}</div>
+        ) : (
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/controls/Controls.tsx:180]: The context-based switching here works very well, nice solution!

**Review by marcelgerber — APPROVED** [review]
