### PR TITLE
fix(grapher): reset timeline on map click for collapsed line charts

### LINKED ISSUE #2309: Map tooltip reads "Click for change over time" but displays a bar chart on click
## Description

This happens for collapsed line charts.

## Expected behaviour

~The tooltip should say "Click to select" (or similar).~ Reset the timeline when clicking on a country,

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/death-rates-from-eating-disorders
2. Hover over Australia
3. Note that it says "Click for change over time"
4. Click
5. Note that a bar chart is displayed

## Screenshots

Screenshot 2023-06-12 at 10 47 39

## Additional context

Would also be fixed by changing the chart type to discrete bar (but that might not be desired)

### PR DESCRIPTION
**Pull request by sophiamersmann**
fixes #2309

For collapsed line charts, clicking on a country in a map currently displays a discrete bar chart with a single bar. It makes more sense to show the full time range instead.

### CODE REVIEW

File: packages/@ourworldindata/grapher/src/core/Grapher.tsx [hunk 1]
```diff
@@ -926,6 +926,11 @@ export class Grapher
         return this.timelineHandleTimeBounds[1]
     }
 
+    @action.bound resetHandleTimeBounds(): void {
+        this.startHandleTimeBound = this.timelineMinTime || -Infinity
+        this.endHandleTimeBound = this.timelineMaxTime || Infinity
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/core/Grapher.tsx:931]:
```suggestion
        this.startHandleTimeBound = this.timelineMinTime ?? -Infinity
        this.endHandleTimeBound = this.timelineMaxTime ?? Infinity
```

Otherwise, we don't handle `0` correctly.
My general rule is to use `??` over `||` whenever possible, it's less surprising in general.

File: packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx [hunk 2]
```diff
@@ -295,6 +295,13 @@ export class MapChart
         if (!ev.shiftKey) {
             this.selectionArray.setSelectedEntities([entityName])
             this.manager.currentTab = GrapherTabOption.chart
+            if (
+                this.manager.isLineChartThatTurnedIntoDiscreteBar &&
+                this.manager.hasTimeline &&
+                this.manager.resetHandleTimeBounds
+            ) {
+                this.manager.resetHandleTimeBounds()
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx:303]:
```suggestion
            if (
                this.manager.isLineChartThatTurnedIntoDiscreteBar &&
                this.manager.hasTimeline
            ) {
                this.manager.resetHandleTimeBounds?.()
```

I _slightly_ prefer this, but both are fine really.

**Review by marcelgerber — CHANGES_REQUESTED** [review]

**Review by marcelgerber — APPROVED** [review]
