### PR TITLE
fix(explorer): show "No data" annotation in map tooltips

### LINKED ISSUE #2054: "No data" annotation in map tooltips does not show up in Explorers
## Description

When hovering over a country in a map _within an explorer_, the "No data" annotation does not show up (see second screenshot).

## Expected behaviour

The tooltips should say "No data (on...)", similar to the tooltips outside explorers (see first screenshot).

## Steps to reproduce

1. Go to [this explorer](https://ourworldindata.org/explorers/coronavirus-data-explorer?tab=map&facet=none&Interval=7-day+rolling+average&Relative+to+Population=false&Color+by+test+positivity=false&country=~CAN&Metric=People+vaccinated) and [this chart](https://ourworldindata.org/grapher/daily-covid-vaccination-doses-per-capita?tab=map)
2. Hover over a country without data (e.g. Canada)
3. Notice that the chart's tooltip says "No data" while the explorer's tooltip is missing the "No data" annotation

## Screenshots

Screenshot 2023-03-28 at 15 19 43
Screenshot 2023-03-28 at 15 20 06

## Environment

For desktop, provide:

-   OS: mac
-   Browser: chrome
-   Version: 113

### PR DESCRIPTION
**Pull request by sophiamersmann**
fixes #2054 

The "No data" annotation in tooltips doesn't show up in explorers, see #2054 for screenshots.

The reason "No data" shows up in charts but not in explorers is that the respective data column in charts is of type `NumberOrStringColumn` while the data column in explorers is of type `NumericColumn`. The `formatValueLong` function behaves differently for `NumberOrStringColumn` and `NumericColumn`. In case of `NumberOrStringColumn`, string values are passed through, in case of `NumericColumn` string values are silenced (returns `""`). That's why the "No data" label doesn't show in explorer maps.

### CODE REVIEW

**Comment by marcelgerber** [comment]
Marcel, in the past: "[Drop unnecessary if condition](https://github.com/owid/owid-grapher/commit/32dfa523f389941b28e3113f0c9b1af604e3dd18)" (as part of https://github.com/owid/owid-grapher/pull/1476)

Well, was it really that unnecessary, past me? 🙃

File: packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import React from "react"
+import { isNumber } from "lodash"
 import {
+    anyToString,
```
Comment (marcelgerber) [inline packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx:4]:
```suggestion
import {
    isNumber,
    anyToString,
```

We need to be a bit careful here - we have the convention that we only import lodash via `@ourworldindata/utils`, because that's a bit better for tree shaking and slightly decreases the size of our assets.

**Review by marcelgerber — COMMENTED** [review]
One small thing that you couldn't possibly know - otherwise this looks good, and good find!

**Comment by sophiamersmann** [comment]
> Marcel, in the past: "[Drop unnecessary if condition](https://github.com/owid/owid-grapher/commit/32dfa523f389941b28e3113f0c9b1af604e3dd18)" (as part of #1476)
> 
> Well, was it really that unnecessary, past me? 🙃

Haha happy to be fixing your bugs while you are fixing Daniels 😄
