### PR TITLE
Moves standalone visualizations to left column

### LINKED ISSUE #1112: Charts without accompanying text should always show in left column
## Core problem

It’s currently the case that if a chart is on its own (without text), it appears in the right column. Example [here](https://ourworldindata.org/food-prices#recent-trends-in-food-price-volatility). This looks a bit broken. Authors can manually put it in the left column, but this is quite a lot of work.

## Proposed solution

We would propose to set two defaults:

- If a single chart appears below a heading without text, it always shows in the left column
- If there are two charts, they automatically show side-by-side in two-column view.

### PR DESCRIPTION
**Pull request by mlbrgl**
resolves #1112 

image (2)

## Special cases

- legacy h6 caption + image combos are not considered standalone figures and are not moved to the left column

Screenshot 2022-02-25 at 14 30 38

- 2n+1 charts are positioned as follows: 2n in a `side-by-side` split, and the remaining one in the left column of a `sticky-left` layout. Reason for not using a `side-by-side` layout for the remaining chart: added complexity not warranted given the low occurrence of that setup.
image

## Developer perspective
- add tests for automatic layout engine (`splitContentIntoSectionsAndColumns()`)
- refactor automatic layout engine using chain of responsibility pattern (baseline tests before refactoring added in #1219)

### CODE REVIEW

File: site/formatting.tsx [hunk 1]
```diff
@@ -63,108 +66,222 @@ export const splitContentIntoSectionsAndColumns = (
...
+    const fullWidthHandler = new FullWidthHandler()
+
+    // Set up chain of responsibility pattern. Elements are being passed
+    // through the chain until a handler can process them.
+    fullWidthHandler
+        .setNext(new H4Handler())
+        .setNext(new SideBySideHandler())
+        .setNext(new StandaloneFigureHandler())
+        .setNext(new FigureHandler())
+        .setNext(new DefaultHandler())
```
Comment (danielgavrilov) [inline site/formatting.tsx:262]: Just to make sure I understand correctly:

- For each element in a section, handlers are executed one by one in order. 
- It's the responsibility of the handler to figure out whether to **1)** apply some transformation, or **2)** do nothing, pass responsibility onto the next handler in the chain.
- A handler should never do both 1) and 2) – both apply a transformation and additionally let other handlers apply transformations. Or is there a case where we might want this? A concrete example: could both `StandaloneFigureHandler` and `FigureHandler` run on a single element?

Is all of that right?

Comment (mlbrgl) [reply site/formatting.tsx:262]: thanks for looking into this @danielgavrilov. Yes that's all correct. 

About the last point, handlers are indeed mutually exclusive: the first one to match returns and breaks the chain. It makes the order of handlers important, e.g. if we were to swap `StandaloneFigureHandler` and `FigureHandler`, `StandaloneFigureHandler` would never match.

The chain is built so that the first handler to match is the right and only one, this is the contract you sign when putting elements through the chain.

I believe a variation of the pattern might allow for overriding behaviour (e.g. express's middleware), but so far I don't see a case where we might need or want this. I can see how this would be different if the chain were to apply layers of subsequent transformations. In this case however, we want to find out which one of these handler is the most suited one, and by design it is the first one to match.

Comment (danielgavrilov) [reply site/formatting.tsx:262]: Right, thanks! All makes sense. I think it might be helpful to have a short summary of these points in the code comment?

**Review by danielgavrilov — APPROVED** [review]

File: site/formatting.tsx (hunk 1 above)
Comment (mlbrgl) [reply site/formatting.tsx]: yep, I reused your bullet points, I think they're very clear 👍
