### PR TITLE
fix: Display data values in DataTable for columns with xOverrideYear

### LINKED ISSUE #1274: Scatterplots with fixed x-axis year have no table values

### PR DESCRIPTION
**Pull request by marcelgerber**
Fixes #1274 | Live on tufte: [One](https://tufte-owid.netlify.app/grapher/smoking-death-rate-1990-2017?tab=table), [Two](https://tufte-owid.netlify.app/grapher/tests-of-covid-19-per-thousand-people-vs-gdp-per-capita?tab=table)

Data tables didn't show these values because they were assuming the `targetTimes` to be the same for every column, and didn't take into account that the `targetTime` can be overriden for some columns.

There's also a slight visual change in the table tab, which is that the `targetTime` is now displayed as part of the column header.
In some cases it is redundant, but it is crucial in many cases. It's always displayed when the timeline is set to a single year.

image

---

### Review notes

9b4ca4a0c9c1f5dfe5a66559c00dd537905d90ae is a refactoring of the `columnsWithValues` method, which was massive.
I did nothing else but to split it up into a few methods. Logically everything is exactly the same.

You can review more easily using 9b4ca4a...e4451ac1ad96e008462e94971ebb49656f7626a5

### CODE REVIEW

File: grapher/dataTable/DataTable.tsx [hunk 1]
```diff
@@ -212,15 +213,26 @@ export class DataTable extends React.Component<{
...
 
             const dimensionHeaderText = (
                 <React.Fragment>
-                    <span className="name">{upperFirst(columnName)}</span>
-                    <span className="unit">{unit}</span>
+                    <div className="name">{upperFirst(columnName)}</div>
+                    <div>
+                        <span className="unit">{unit}</span>{" "}
+                        <span className="divider">
+                            {unit && targetTime !== undefined && "•"}
```
Comment (danielgavrilov) [inline grapher/dataTable/DataTable.tsx:229]: nit: might be nice to use the proposition (e.g. `in` or `on`) instead of a bullet? Only if it's easy 😬

Comment (marcelgerber) [reply grapher/dataTable/DataTable.tsx:229]: I thought about that! But I don't think it always fits in super nicely with the unit, and I like the visual distinction between the two.

One example where it's not great is "Total tests": there the unit is `Tests performed`, and if we make it `Tests performed on May 29, 2022` it becomes misleading.

Comment (danielgavrilov) [reply grapher/dataTable/DataTable.tsx:229]: Good point! Makes sense to keep it separated with a •

**Comment by larsyencken** [comment]
Thanks @marcelgerber, it's awesome to see tables gradually tightening up for grapher!
