### PR TITLE
Fix autocomplete dropdown position

### LINKED ISSUE #5073: Autocomplete Dropdown Layout Broken in Navbar Search
# Autocomplete Dropdown Layout Broken in Navbar Search

## Bug Description
The layout of content in the autocomplete dropdown is broken when opening the search box from the navbar. This issue does not occur when using the homepage search box.

## Screenshots

| Broken Layout (Navbar Search) | Correct Layout (Homepage Search) |
|--------------------------------|-----------------------------------|
| Broken autocomplete dropdown layout from navbar search | Correct autocomplete dropdown layout from homepage search |

*Note: Screenshots to be added showing the layout differences*

## Steps to Reproduce
1. Navigate to any page with the navbar search
2. Click on the search box in the navbar
3. Observe the autocomplete dropdown layout

## Expected Behavior
The autocomplete dropdown should display properly formatted content with correct spacing and alignment, similar to how it appears when using the homepage search box.

## Actual Behavior
The content layout within the autocomplete dropdown appears broken/misaligned when opened from the navbar search.

## Workaround
The layout returns to normal when:
1. Resizing the browser window out of the `md` breakpoint
2. Resizing back into the `md` breakpoint

## Additional Notes
- Issue occurs on page load
- Issue persists on subsequent opening/closing of the detached autocomplete
- Even after fixing through the resize workaround described above, the issue reoccurs on subsequent uses
- Only affects navbar search, not homepage search box
- Appears to be related to responsive breakpoints (specifically `md` breakpoint)

## Environment
- Browser: [To be filled]
- Screen size: Within `md` breakpoint range
- Device: [To be filled]

## Priority
Medium - Affects user experience but has a workaround

### PR DESCRIPTION
**Pull request by rakyi**
There was a range of widths at which we were manually setting the dropdown position when we shouldn't have.

Fixes #5073

### CODE REVIEW

File: site/SiteNavigation.tsx [hunk 1]
```diff
@@ -59,7 +62,7 @@ export const SiteNavigation = ({
         // Fortunately we only have to do this when it mounts - it takes care of resizes
         setTimeout(() => {
             // Only run when screen size is large, .aa-DetachedContainer gets positioned correctly
-            if (window.innerWidth < 768) return
+            if (window.innerWidth < DETACHED_MODE_MAX_WIDTH) return
```
Comment (mlbrgl) [inline site/SiteNavigation.tsx]: "<=" here to match the max-width media query (otherwise 1045 viewports still misbehave)

**Comment by mlbrgl** [comment]
Screenshot 2026-03-13 at 08 55 29

the modal experience that would be triggered between md and lg with proper var interpolation

File: site/SiteNavigation.tsx (hunk 1 above)
Comment (rakyi) [reply site/SiteNavigation.tsx]: Good catch!

**Comment by rakyi** [comment]
The var interpolation is an even better catch! Created #6229 for it.
