### PR TITLE
Fix deleted assets staying in Cloudflare cache

### LINKED ISSUE #2896: When deleting content (WP/Gdocs/charts), set up a redirect to ensure immediate inaccessibility
Cloudflare can cache content for a while after it is no longer part of our bake. If we want to ensure that content is no longer reachable immediately after we delete it we should make sure to set up redirects from the old slug to the homepage or a better redirect target.

## Original problem description

We recently made some old job postings private in Wordpress, but they did not get removed from the bake.

e.g. [Data analyst](https://ourworldindata.org/data-analyst-econ), [Comms manager](https://ourworldindata.org/communications-outreach-manager-q4-2023)

## Expected behaviour

When you change the visibility of a post, it should be excluded in the next bake.

/cc @CGiattino

### PR DESCRIPTION
**Pull request by rakyi**
When we delete a post it no longer gets baked and is thus not present in the next CF Pages deployment. However, assets can stay in the CF Pages cache for up to a week and we want them to be inaccessible right away, e.g. for job postings.

I verified that this works both locally and on staging, including deployment to staging Pages.

Fixes #2896

### CODE REVIEW

File: adminSiteServer/apiRouter.ts [hunk 1]
```diff
@@ -2468,6 +2470,15 @@ deleteRouteWithRWTransaction(apiRouter, "/gdocs/:id", async (req, res, trx) => {
...
         await removeIndividualGdocPostFromIndex(gdoc)
     }
+    // Assets have TTL of one week in Cloudflare. Add a redirect to make sure
+    // the page is no longer accessible.
+    // https://developers.cloudflare.com/pages/configuration/serving-pages/#asset-retention
+    const ttl = dayjs().add(8, "days").toDate()
+    await db.knexRawInsert(
+        trx,
+        `INSERT INTO redirects (source, target, ttl) VALUES (?, ?, ?)`,
+        [getCanonicalUrl("", gdoc), "/", ttl]
```
Comment (marcelgerber) [inline adminSiteServer/apiRouter.ts:2480]: I _slightly_ prefer the timestamp computation to also be happening within MySQL syntax.
That way, there's no way for there to be weird timezone or other issues between the two. And thankfully, the MySQL syntax for this is still pretty readable.

```suggestion
        `INSERT INTO redirects (source, target, ttl) VALUES (?, ?, DATE_ADD(NOW(), INTERVAL 8 DAY) )`,
        [getCanonicalUrl("", gdoc), "/"]
```

**Review by marcelgerber — APPROVED** [review]
Nice, I feel like this is a good solution to the problem

File: adminSiteServer/apiRouter.ts (hunk 1 above)
Comment (rakyi) [reply adminSiteServer/apiRouter.ts]: Good idea! Changed.
