### PR TITLE
fix(algolia): index explorers even if they're grapherId-powered

### LINKED ISSUE #2622: Grapher powered explorers are not indexed
## Expected behavior

All explorers, regardless of the way they were built, should be indexed.

## Steps to reproduce

1. [Search for democracy](https://ourworldindata.org/search?q=democracy)
2. The [democracy explorer](https://ourworldindata.org/explorers/democracy) is not returned

## Resolution
see [RCA and suggested resolution by @marcelgerber](https://owid.slack.com/archives/C014SGT6W9X/p1694086606677299?thread_ts=1694075613.712229&cid=C014SGT6W9X)

## Screenshots

Screenshot 2023-09-07 at 13 44 05

### PR DESCRIPTION
**Pull request by marcelgerber**
Resolves #2622.

### CODE REVIEW

File: baker/algolia/indexExplorersToAlgolia.ts [hunk 1]
```diff
@@ -99,17 +141,25 @@ const getExplorerRecords = async (): Promise<ExplorerRecord[]> => {
...
                 )
+
+                // In case we don't have any text for this explorer, we still want to index it
+                const textChunksForIteration = textChunks.length
+                    ? textChunks
+                    : [""]
                 const explorerRecords = []
                 let i = 0
-                for (const chunk of textChunks) {
+                for (const chunk of textChunksForIteration) {
```
Comment (mlbrgl) [inline baker/algolia/indexExplorersToAlgolia.ts:162]: (not introduced in this PR)
nit: seems like a forEach would be more fitting here?

**Review by mlbrgl — APPROVED** [review]
It looks like this closes the loop nicely on explorer indexing!

I like that you went all the way to the grapher config to get the charts' title and subtitle. Feels very thorough.

File: baker/algolia/indexExplorersToAlgolia.ts (hunk 1 above)
Comment (marcelgerber) [reply baker/algolia/indexExplorersToAlgolia.ts]: Yeah, or `map` for that matter. Thanks! :)
