### PR TITLE
different fix: Axis tick labels shows proper decimal places

### LINKED ISSUE #1267: Axis tick labels do not include sufficient decimal places for small values
## Description

Axis tick labels sometimes do not include sufficient decimal places.

## Expected behaviour

Axis ticks should display enough decimal places to be meaningful.

## Example

https://ourworldindata.org/grapher/share-of-cumulative-co2?tab=chart&time=latest&country=~MKD

## Screenshots

image

### PR DESCRIPTION
**Pull request by marcelgerber**
Fixes #1267, but in a different way to #1394.

I feel like this is the more sensible way to go about this problem.
The main difference here is this one here in the output of `HorizontalAxis.baseTicks`:

```diff
  [
-   { value: 0, priority: 2 },
+   { value: 0, priority: 1 },
    { value: 0.00005, priority: 2 },
    { value: 0.0001, priority: 2 },
    { value: 0.00015, priority: 2 },
    { value: 0.0002, priority: 2 },
    { value: 0.00025, priority: 2 },
    { value: 0.0003, priority: 2 },
    { value: 0.00035, priority: 2 },
    { value: 0.0004, priority: 2 }
  ]
```

In addition, I added a test case (which passes for both the old & new fix, and fails without them) which we should get in either way :)

### CODE REVIEW

**Comment by marcelgerber** [comment]
One example difference is [this one here](http://localhost:3030/admin/test/embeds?ids=20&comparisonUrl=https%3A%2F%2Fourworldindata.org) (in a small viewport):
image

**Comment by marcelgerber** [comment]
Also, the SVG diffs seem to come from the changed order of tick labels: Tick labels are placed in the order `[priority, value]`, and hence the order of them in the SVG has changed too.

File: grapher/axis/Axis.ts [hunk 1]
```diff
@@ -462,32 +463,28 @@ export class HorizontalAxis extends AbstractAxis {
...
                     value: domain[1],
                     priority: startEndPrio,
                 },
             ]
-        return uniq(ticks)
+
+        // sort by value, then priority.
+        // this way, we don't end up with two ticks of the same value but different priorities.
+        // instead, we deduplicate by choosing the highest priority (i.e. lowest priority value).
+        const sortedTicks = sortBy(ticks, (tick) => [tick.value, tick.priority])
```
Comment (danielgavrilov) [inline grapher/axis/Axis.ts:486]: I think we need to use [`orderBy`](https://lodash.com/docs/4.17.15#orderBy) because `sortBy` seems to compare arrays by their string value?

```ts
_.sortBy([[100, 1], [30, 1], [1, 1]], (d) => d) 
// [
//   [1, 1]
//   [100, 1]
//   [30, 1]
// ]
```

I _think_ this should work:

```suggestion
        const sortedTicks = orderBy(ticks, [(t) => t.value, (t) => t.priority])
```

**Comment by danielgavrilov** [comment]
Ooops, good catch! Thanks for reviewing the PRs!

File: grapher/axis/Axis.ts (hunk 1 above)
Comment (marcelgerber) [reply grapher/axis/Axis.ts]: Ooh, that is a very good catch! Thank you.
