### PR TITLE
Topic page fixes

### LINKED ISSUE #2256: Additional charts block currently isn't rendering correctly
This component is meant to be a way to add a list that adds little SVG arrows to the right of the links.

```
[.additional-charts]
- [Here’s a link](https://ourworldindata.org/)
- [Here’s another on](https://ourworldindata.org/)e
[]
```

But it's currently not rendering correctly

image

Possibly because of the [recent fix to list parsing](https://github.com/owid/owid-grapher/commit/c1bec352250c18e0d4317e04e782beaa9acb3495).

To fix this we may want to change the model slightly in archie, in which case we'll also need to add a migration for any existing archie that uses this block.

### PR DESCRIPTION
**Pull request by ikesau**
Fixes  #2256

1. Correctly provision all-charts block with `relatedCharts` when baking
2. Show "Untitled" if a registered document doesn't yet have a title (so you can still click on it)
3. Set slug correctly
4. CSS touchups
5. Auto-update unpublished gdocs on GET
6. Fix archie for nested lists in `additional-charts` and `chart-story`
   - This doesn't require a migration because it only affects the raw shape. This means it will have to be fixed in the source gdoc before one can republish, but I've explained that explicitly in the error messages.

image

image

### CODE REVIEW

**Comment by ikesau** [comment]
Reminder to update the [docs](https://docs.google.com/document/d/1OLoTWloy4VecOjKTjB1wLV6tEphHJIMXfexrf1ZYJzU/edit) once this is merged.

File: adminSiteClient/GdocsSettingsContentField.tsx [hunk 1]
```diff
@@ -45,8 +48,8 @@ export const GdocsSettingsContentField = ({
                     errorType: error?.type,
                 })}
             </div>
-
             <GdocsErrorHelp error={error} />
```
Comment (marcelgerber) [inline adminSiteClient/GdocsSettingsContentField.tsx:51]: not part of this PR at all, but I'm a bit confused about the `GdocsErrorHelp` block.
That it can _either_ show an error message _or_ a help block, and never both, is a bit weird to me.

**Review by marcelgerber — APPROVED** [review]
Yeah makes sense to me, but also I don't know too much about the gdocs pipeline so take this with a grain of salt!
