### PR TITLE
🐛 Fix markdown regeneration for Gdocs

### LINKED ISSUE #5436: Algolia pages records out of sync with content
Algolia's pages indexing script uses the DB gdoc.markdown property as its source to generate records. However, this property is not always kept in sync with the actual gdoc.content used for rendering.

Failure modes: 
- create gdoc and publish without saving as draft first -> no markdown in the DB
- update published gdoc -> old markdown not regenerated

Impact: all updated gdoc since the introduction of this issue will continue to match on their original content, introducing a growing number of mismatches in search results.

There is an `updateMarkdown` function on the GdocBase class, but it is currently unused, possibly after a partial refactoring.

What works? The markdown is updated when saving a draft.

Suggested solution:
- regenerate the markdown on every DB save, likely in `upsertGdoc`
- one time: regenerate all markdowns in the DB

Temporary solution:
- recompute all markdown fields during indexing

Context: [slack](https://owid.slack.com/archives/C46U9LXRR/p1758719174740599)

### PR DESCRIPTION
**Pull request by danyx23**
Fixes #5436. Markdown generation was initially an experimental feature, but more and more pieces of our codebase rely on this field being up-to-date. At one point, a refactor must have broken markdown regeneration on post updates. This PR fixes this issue.

### CODE REVIEW

**Comment by danyx23** [comment]
* **#5644** <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5644?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: devTools/regenerateGdocMarkdown.ts [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+
+            if (id) break
+            offset += rows.length
+            console.log(
+                `Processed ${processed}/${total} documents (${updated} updated so far)`
+            )
+        }
+
+        console.log(
+            `Finished regenerating markdown. Updated ${updated} of ${processed} documents.`
```
Comment (ikesau) [inline devTools/regenerateGdocMarkdown.ts]: One very tiny thing that wasn't obvious about this message when I ran this locally is that there is some number of documents that don't get updated because their markdown is already correct.

Reading the implementation makes it clear, but at first I thought I had a bunch of silent errors.

File: db/model/Gdoc/upsertGdoc.test.ts [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+vi.mock("./extractGdocComponentInfo.js", () => ({
+    getGdocComponentsWithoutChildren: (): never[] => [],
+}))
+
+// The tests in this file mock all the database calls and are only used to verify
+// that the markdown regeneration logic is correctly triggered before saving.
+// There is a separate integration test in adminSiteServer/tests/gdocs-markdown.test.ts
+// that verifies end-to-end that the markdown is correctly regenerated and saved.
+// If this test should be annoying for some reason, feel free to delete it as long
+// as the other test remains.
```
Comment (ikesau) [inline db/model/Gdoc/upsertGdoc.test.ts]: Given that we have the E2E test, what's the upside of this test?

I've confirmed it does what it says on the tin, but it's quite a lot mocking / random new code to test something we're already testing.

Is the hope that we might want to test more DB logic like this in the future without it being coupled to the admin?

**Comment by danyx23** [comment]
Nice, thanks for the fix and the feedback!

File: db/model/Gdoc/upsertGdoc.test.ts (hunk 2 above)
Comment (danyx23) [reply db/model/Gdoc/upsertGdoc.test.ts]: Yeah I'm on the fence if this is useful. Codex wrote this so it was cheap to add but its maybe better to be more deliberate about whether to add such mock-heavy tests. Removing this.
