### PR TITLE
✨ disable switching from line to bar chart via the timeline

### LINKED ISSUE #5223: Inconsistent tab between URL param and UI
## Description

In some cases there can be an inconsistency between the tab query param in the URL and the selected tab in the UI.

Discovered [here](https://github.com/owid/owid-grapher/pull/5091#discussion_r2239047145).

## Expected behaviour

When I go to a data page and the URL query param is `?tab=line` I expect the line tab to be selected.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/human-development-index?tab=line
2. Observer that:
   - Query param is `?tab=line`
   - UI shows a bar tab with a bar chart

## Screenshots

Image

## Environment

For desktop, provide:

- OS: macOS
- Browser: Firefox 141.0

### LINKED ISSUE #5568: Allow users to add another time handle to bar charts
## Core problem

Why is it that users can switch from a line chart to a bar chart by dragging the time handle but they can’t then switch back from bar chart to line chart by adding a date to the chart?

## Proposed solution

Allow users to add another date to bar charts to switch back to line charts. 

This might have been a regression when the bar charts were added as their own tab. The behaviour we want is similar to the one we have for the table tab.

## Context

Slack thread between Marwa and Sophia [here](https://owid.slack.com/archives/C5BDCB2R3/p1761054348365029)

### PR DESCRIPTION
**Pull request by sophiamersmann**
Resolves #5223, resolves #5568

Disables switching from a line/slope to a bar chart via the timeline, as discussed. End of an era!

The migration should take care of all charts where the discrete bar chart is currently the default implicitly. If you check the charts reported by the SVG tester on staging, they should look unchanged.

### CODE REVIEW

**Comment by sophiamersmann** [comment]
* **#5864** <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5864?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5790** <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5790?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5761** <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5761?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5747** <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5747?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#5746** <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5746?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/owid/owid-grapher/5746?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by marcelgerber** [comment]
@codex review

File: db/migration/1764661863496-DisableLineBarChartSwitching.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+                    OR (
+                        JSON_SEARCH(cc.full -> '$.chartTypes', 'one', 'LineChart') IS NOT NULL
+                        AND JSON_SEARCH(cc.full -> '$.chartTypes', 'one', 'DiscreteBar') IS NOT NULL
+                    )
+                )
+                -- Only update charts with identical minTime and maxTime (i.e. the bar chart is initially shown)
+                AND (
+                    cc.full ->> '$.minTime' = cc.full ->> '$.maxTime'
+                    OR (cc.full ->> '$.minTime' = 'latest' AND cc.full ->> '$.maxTime' IS NULL)
+                    OR (cc.full ->> '$.minTime' IS NULL AND cc.full ->> '$.maxTime' = 'earliest')
```
Comment (marcelgerber) [inline db/migration/1764661863496-DisableLineBarChartSwitching.ts]: I think this is cleaner and easier using `COALESCE`:

```suggestion
                    COALESCE(cc.full ->> '$.minTime', 'earliest') = COALESCE(cc.full ->> '$.maxTime', 'latest')
```

Comment (sophiamersmann) [reply db/migration/1764661863496-DisableLineBarChartSwitching.ts]: Nice!

**Comment by sophiamersmann** [comment]
### Merge activity

* **Dec 4, 2:42 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/owid/owid-grapher/5746).
* **Dec 4, 2:42 PM UTC**: @sophiamersmann merged this pull request with [Graphite](https://app.graphite.com/github/pr/owid/owid-grapher/5746).
