### PR TITLE
Autofocus search input only when it's empty

### LINKED ISSUE #5930: Keyboard autofocuses unexpectedly when selecting "data" or "writing" filters on mobile
A bit of friction on search on mobile: when a user clicks on “data” or “writing”, the keyboard pops up unsolicited and blocks the content.

[Slack Message](https://owid.slack.com/archives/C06UA61V85U/p1768468782595599)

### PR DESCRIPTION
**Pull request by rakyi**
Improves accessibility and fixes #5930.

### CODE REVIEW

File: site/search/Search.tsx [hunk 1]
```diff
@@ -67,6 +68,11 @@ export const Search = ({
 
     const isFetching = useIsFetching()
 
+    const isFirstMountRef = useRef(true)
+    const shouldAutoFocus =
+        isFirstMountRef.current && isBrowsing(state.filters, state.query)
+    isFirstMountRef.current = false
```
Comment (mlbrgl) [inline site/search/Search.tsx]: we should technically not update the ref during render but fine here if you have a good reason to do so

Comment (rakyi) [reply site/search/Search.tsx]: I copied the code from [your PR](https://github.com/owid/owid-grapher/pull/6131/changes). 😄 But a good point, changed.

**Comment by rakyi** [comment]
Added the test.

**Comment by mlbrgl** [comment]
thanks! 🙏
