### PR TITLE
fix(grapher): fix domain extent for scatter plots with few data points

### LINKED ISSUE #1332: ScatterPlot: Use X/Y min/max from config when only a single bubble is plotted
## Description

> The x axis in this chart sometimes includes negative values when scrolling through early years e.g. 1793-4, the values in the data are limited to 0-1.

https://ourworldindata.org/grapher/life-expectancy-vs-liberal-democracy?time=1790

life-expectancy-vs-liberal-democracy

The chart has X min/max defined by authors:

Screenshot 2022-03-29 at 15 10 20

The issue is probably in this bit of code

https://github.com/owid/owid-grapher/blob/4417e7515fea7473a819aae7112445908070ebef/grapher/scatterCharts/ScatterPlotChart.tsx#L821-L840

## Expected behaviour

X/Y min/max should be respected when set.

### PR DESCRIPTION
**Pull request by sophiamersmann**
Fixes the issue described in #1332 by respecting the author's domain extent setting for data sets with a single unique value along an axis.

What happens is that basically if there is only one (unique) value along an axis, the extent of the domain is set to a reasonable default that is (in case of linear scales) `[unique_value - 1, unique_value + 1]`.  The author's setting is then taken into account by _expanding_ (but never _shrinking_) the computed extent. In most cases, that's fine. But when the computed extent was set to `[unique_value - 1, unique_value + 1]`, and thus "overshoots" the actual data range to both sides, then this is not corrected for when taking into account the author's domain setting. Check out [this chart](https://ourworldindata.org/grapher/life-expectancy-vs-liberal-democracy?time=1791). It is important to note that this is usually only perceived as an issue if a certain range of values along an axis are non-sensical (e.g. a scale from 0-1 where negative values don't have any meaning).

I fixed this by making sure the author's domain setting is respected when the dataset consists of a single unique value along an axis. This comes with two caveats though:
- this might lead to erratic jumps when animating through the years (some years might only have a single data value, others more)
- data points might be unintentionally hidden by enforcing the author's setting

Both of these caveats actually happen for [this chart](https://ourworldindata.org/grapher/life-expectancy-vs-liberal-democracy?time=1791) where the author set the x-axis to `[0, 1]` and the y-axis to `[50,85]`. So... we might want to do something more intelligent? ... Or add another option to allow the user to choose whether they want their domain setting to be enforced in all cases? ... Or something else?

closes #1332

### CODE REVIEW

File: packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx [hunk 1]
```diff
@@ -822,6 +822,14 @@ export class ScatterPlotChart
...
     }
 
+    private validValuesForAxisDomain(property: "x" | "y"): number[] {
+        const scaleType = property === "x" ? this.xScaleType : this.yScaleType
+        const values = this.pointsForAxisDomains.map((point) => point[property])
+        return scaleType === ScaleType.log
+            ? values.filter((v) => v > 0)
+            : values
+    }
+
```
Comment (danyx23) [inline packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx:832]: This is a bit dangerous and should be done as a @computed property instead. The reason for this is the following: here you have a member function that accesses several mobx computed properties. But because it itself is just a function it is not going to be automatically recomputed when one of the inputs change. On top of this, the call site in `vertical/horizontalAxisPart` is in one branch of an if.

Mobx computed properties track their dependencies and cache results, but they only work correctly if the places that create derived values are wrapped in `@computed` properties and if they are read unconditionally. 

Therefore it probably makes sense to turn this function into two computed properties, one for x and one for y values. At the site of use, this property should then be read at the top of the property body so that the dependency will be tracked regardless of which of the two if blocks is executed.

**Review by danyx23 — CHANGES_REQUESTED** [review]
This gets the job done but it has a potential issue in how the valid values are computed - see the inline comment.

File: packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx (hunk 1 above)
Comment (sophiamersmann) [reply packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx:832]: Makes perfekt sense, will do tomorrow. Thanks for explaining!

**Review by marcelgerber — APPROVED** [review]
LGTM!

**Comment by marcelgerber** [comment]
This is ready to be merged from my point of view now :)

**Review by danyx23 — APPROVED** [review]
LGTM - nice work!
